
TEAMS = [
			('WAS', 'Washington', 'Nationals'),
			('PIT', 'Pittsburgh', 'Pirates'),
			('NYM', 'New York', 'Mets'),
			('ATL', 'Atlanta', 'Braves'),
			('LAD', 'Los Angelas', 'Dodgers'),
			('ARI', 'Arizona', 'Diamondbacks'),
			('NYY', 'New York', 'Yankees'),
			('HOU', 'Houston', 'Astros'),
			('DET', 'Detroit', 'Tigers'),
			('KAN', 'Kansas City', 'Royals'),
			('BOS', 'Boston', 'Red Sox'),
			('TEX', 'Texas', 'Rangers'),
			('CHW', 'Chicago', 'White Sox'),
			('MIN', 'Minnesota', 'Twins'),
			('LAA', 'Los Angelas', 'Angels'),
			('BAL', 'Baltimore', 'Orioles'),
			('OAK', 'Oakland', 'Athletics'),
			('SEA', 'Seattle', 'Mariners'),
			('TOR', 'Toronto', 'Blue Jays'),
			('CLE', 'Clevland', 'Indians'),
			('TAM', 'Tampa Bay', 'Rays'),
			('MIL', 'Milwaukee', 'Brewers'),
			('CHC', 'Chicago', 'Cubs'),
			('STL', 'St. Louis', 'Cardinals'),
			('COL', 'Colorado', 'Rockies'),
			('SFO', 'San Francisco', 'Giants'),
			('MIA', 'Miami', 'Marlins'),
			('PHI', 'Philadelphia', 'Phillies'),
			('CIN', 'Cincinnati', 'Reds'),
			('SDG', 'San Diego', 'Padres')
		]   